import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': 'rgb(var(--color-background) / <alpha-value>)',
        'on-surface-variant': '#424844',
        'surface-tint': '#466557',
        'primary': 'rgb(var(--color-primary) / <alpha-value>)',
        'inverse-on-surface': '#f5f0e7',
        'surface-bright': '#fef9f0',
        'secondary-fixed-dim': '#e7bdb1',
        'error': '#ba1a1a',
        'secondary-fixed': '#ffdbd0',
        'secondary': 'rgb(var(--color-secondary) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'tertiary-fixed': '#d0e6f3',
        'on-secondary-fixed-variant': '#5d4037',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'on-secondary-container': '#795950',
        'on-primary-container': '#99baa9',
        'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
        'on-primary-fixed': '#012116',
        'on-tertiary-container': '#a1b6c3',
        'primary-container': '#2d4b3e',
        'on-primary-fixed-variant': '#2f4d40',
        'primary-fixed': '#c8ead8',
        'inverse-primary': '#adcebd',
        'tertiary-container': '#344853',
        'secondary-container': '#fed3c7',
        'tertiary': 'rgb(var(--color-tertiary) / <alpha-value>)',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#081e27',
        'surface-container-lowest': '#ffffff',
        'outline': '#727974',
        'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface': '#fef9f0',
        'primary-fixed-dim': '#adcebd',
        'on-tertiary-fixed-variant': '#364954',
        'on-secondary': '#ffffff',
        'surface-dim': '#ded9d1',
        'on-secondary-fixed': '#2c160e',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'on-surface': '#1d1c16',
        'tertiary-fixed-dim': '#b4cad6',
        'on-background': 'rgb(var(--color-on-background) / <alpha-value>)',
        'outline-variant': '#c1c8c3',
        'inverse-surface': '#32302a',
        'on-tertiary': '#ffffff',
        'chess-inaccuracy': 'rgb(var(--chess-inaccuracy) / <alpha-value>)',
        'chess-success': 'rgb(var(--chess-success) / <alpha-value>)',
        'chess-danger': 'rgb(var(--chess-danger) / <alpha-value>)',
        'chess-warning': 'rgb(var(--chess-warning) / <alpha-value>)',
        'chess-draw': 'rgb(var(--chess-draw) / <alpha-value>)',
      },
      fontFamily: {
        'headline': ['Noto Serif', 'serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [
    forms,
  ],
}


