/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': '#fef9f0',
        'on-surface-variant': '#424844',
        'surface-tint': '#466557',
        'primary': '#163428',
        'inverse-on-surface': '#f5f0e7',
        'surface-bright': '#fef9f0',
        'secondary-fixed-dim': '#e7bdb1',
        'error': '#ba1a1a',
        'secondary-fixed': '#ffdbd0',
        'secondary': '#77574d',
        'surface-container': '#f2ede4',
        'tertiary-fixed': '#d0e6f3',
        'on-secondary-fixed-variant': '#5d4037',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-secondary-container': '#795950',
        'on-primary-container': '#99baa9',
        'surface-variant': '#e7e2d9',
        'on-primary-fixed': '#012116',
        'on-tertiary-container': '#a1b6c3',
        'primary-container': '#2d4b3e',
        'on-primary-fixed-variant': '#2f4d40',
        'primary-fixed': '#c8ead8',
        'inverse-primary': '#adcebd',
        'tertiary-container': '#344853',
        'secondary-container': '#fed3c7',
        'tertiary': '#1e323c',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#081e27',
        'surface-container-lowest': '#ffffff',
        'outline': '#727974',
        'surface-container-high': '#ece8df',
        'surface': '#fef9f0',
        'primary-fixed-dim': '#adcebd',
        'on-tertiary-fixed-variant': '#364954',
        'on-secondary': '#ffffff',
        'surface-dim': '#ded9d1',
        'on-secondary-fixed': '#2c160e',
        'surface-container-highest': '#e7e2d9',
        'on-surface': '#1d1c16',
        'tertiary-fixed-dim': '#b4cad6',
        'on-background': '#1d1c16',
        'outline-variant': '#c1c8c3',
        'inverse-surface': '#32302a',
        'on-tertiary': '#ffffff',
        'chess-inaccuracy': '#e67e22',
        'chess-success': '#27ae60',
        'chess-danger': '#e74c3c',
        'chess-warning': '#f39c12',
        'chess-draw': '#7f8c8d',
      },
      fontFamily: {
        'headline': ['Noto Serif', 'serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}


